id = "bamboo-icons"
name = "Bamboo Icons"
version = "0.0.1"
schema_version = 1
authors = ["Chris Drackett"]
description = "Icons with color and body for Zed."
repository = "https://github.com/chrisdrackett/bamboo-icon-theme-zed"
